name: Terraform Cloud Run Dev

on:
  push:
    branches: [ main ]
    paths: [ 'environments/dev/**', 'modules/cloudrun/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'environments/dev/**', 'modules/cloudrun/**' ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: .
    
    - name: Terraform Init
      run: terraform init
      working-directory: environments/dev
    
    - name: Terraform Validate
      run: terraform validate
      working-directory: environments/dev
    
    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: environments/dev
      continue-on-error: true
